### ISSUE TITLE
Latest update broke the theme plugins

### ISSUE THREAD

**Issue by susta** [lankydan/palenight-intellij-theme#4]
I love both palenight and fairyfloss themes but latest update broke them. It gives this error

> Plugin 'Palenight' (version '0.0.9') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is RD-231.8109.212

I use Rider. Thanks.

**Comment by lankydan** [comment]
A new version of the plugin will be released in the coming days (pending approval), sorry about the wait.
